# Colors used in commands and feedback
Color:
  Main: "&6"
  Secondary: "&f"
#
#
Teleport_On_Join: false
#
# Icon options for the Join Battle UI
Join_UI:
  Join_Battle:
    Icon:
      Name: "&6Join Battle"
      Material: IRON_SWORD
      Durability: 0
      Lore:
      - "&7Battle: %battle%"
      - "&7Players: %players%"
  Create_Battle:
    Icon:
      Name: "&6Create Duel"
      Material: DIAMOND_SWORD
      Durability: 0
      Lore: []
#
# Icons for the Battle Picker UI
Battle_Creator:
  Start_Game:
    Name: "&6Start Game"
    Material: DIAMOND_SWORD
    Durability: 0
    Lore: []
  No_Free_Arena:
    Name: "&6No Free Arenas"
    Material: BARRIER
    Durability: 0
    Lore: []
  Duel:
    Name: "&6Duel"
    Material: DIAMOND_SWORD
    Durability: 0
    Lore:
    - "&71v1"
  FFA:
    Name: "&6FFA"
    Material: IRON_SWORD
    Durability: 0
    Lore:
    - "&7No teams, all against all"
  Team:
    Name: "&6Team Battle"
    Material: IRON_CHESTPLATE
    Durability: 0
    Lore:
    - "&7Two teams, friendly fire disabled"
  Grace_Period:
    Name: "&6Grace Period"
    Material: IRON_CHESTPLATE
    Durability: 0
    Lore:
    - "&7Duration: &f%graceperiod%"
  Battle_Duration:
    Name: "&6Battle Duration"
    Material: WATCH
    Durability: 0
    Lore:
    - "&7Time Limit: &f%battleduration%"